INSERT INTO TIPO_LOCALIDADE (DESCRICAO) VALUES ('Terminal de Integração');
INSERT INTO TIPO_LOCALIDADE (DESCRICAO) VALUES ('Rua');
INSERT INTO TIPO_LOCALIDADE (DESCRICAO) VALUES ('Avenida');

INSERT INTO PREFIXO (SIGLA, DESCRICAO) VALUES ( 'A', 'Alimentador' );
INSERT INTO PREFIXO (SIGLA, DESCRICAO) VALUES ( 'T', 'Troncal' );
INSERT INTO PREFIXO (SIGLA, DESCRICAO) VALUES ( 'C', 'Circular' );